### PR TITLE
add xxhash support for rsync

### PR DESCRIPTION
**Pull request by nwaizer**

### CODE REVIEW

**Comment by HanPrower** [comment]
Thanks for the PR, however, this should be included in the `rysnc` file as it's a dependency for `rsync`, not in a seperate file ran before it (the modules in the main yml are alphabetical).

You can look at `imagemagick`, and the `boost` sub-module for how to do it.

**Comment by nwaizer** [comment]
done as suggested

**Comment by HanPrower** [comment]
So, for some reason, rsync just can't see xxhash.h when trying to build the xxhash support.

I tried for a bit when I realized the bot was failing your build, but it just doesn't want to see it.

You can see basically any Flatpak that uses rsync disables xxhash: https://github.com/search?q=org%3Aflathub+rsync&type=code

I'll leave this open in case someone figures it out, but it may require rsync itself to update to better support the install location of the file? I'm not sure...

**Comment by nwaizer** [comment]
@HanPrower thi seems like the build order is to blame.
I need xxhash to build first and only then rsync, and then it works.
when using separate yml files, this worked fine.

**Comment by HanPrower** [comment]
The original build after you submitted the PR failed (it just looks weird because I cancelled it when it did instead of letting it fail normally).

The other build you made for flathub/com.jetbrains.GoLand#42 worked originally because [you forgot to remove `--disable-xxhash`](https://github.com/flathub/com.jetbrains.GoLand/compare/5497d57ef81a9b98d7bfd775cbcd2310f75f4433..6d68a122b91a38ab7da7edd27cc7afa35751ca10#diff-9a487e6de407e9111ca188e4945c497cfea10356c043732b7124597cbb23a751R8), once you rearranged the files and removed that line it failed.

**Pull request closed without merging**
